### ISSUE TITLE
Modify UBOOT_EXTLINUX_ROOT 

### ISSUE THREAD

**Issue by m5p3nc3r** [superna9999/meta-meson#107]
On my Vim3, when booting I need to modify the UBOOT_EXTLINUX_ROOT to /dev/mmcblk1p1.  With the current recipes, it is not possible to do this in my local.conf because it has a hard assignment in conf/machine/<machine>.conf.

Would you accept a PR that changes the line

UBOOT_EXTLINUX_ROOT = "root=/dev/mmcblk0p1"
 to
UBOOT_EXTLINUX_ROOT ?= "root=/dev/mmcblk0p1"

as this would not change the default behaviour, but allow me to change the default to what I need?

If so, should I create a PR just for the vim3, or should I make the modification for all platforms that use UBOOT_EXTLINUX_ROOT?

**Comment by superna9999** [comment]
sure no problem do the change for all platforms

**Comment by m5p3nc3r** [comment]
Do you want it against the master branch?

**Comment by superna9999** [comment]
yes, I'll push manually on the other branches

**Comment by m5p3nc3r** [comment]
Created PR #108
