### ISSUE TITLE
UNPACKDIR is not set on scarthgap

### ISSUE THREAD

**Issue by philippgl** [superna9999/meta-meson#157]
**Describe the bug**

When compiling some merged #149 I get the following funny looking error;
...
| /home/pglaser/git/bif/scarthgap/radxa-zero/tmp/work/radxa_zero-poky-linux/shadow-securetty/4.6/temp/run.do_configure.808231: 140: cannot create /securetty: Permission denied
...

I skipped the rest of the template, b/c I think, the UNPACKDIR was introduced on master and does not exist in the scarthgap branch.
I would suggest adding a scarthgap branch based on the previous head and removing scarthgap from the 
`LAYERSERIES_COMPAT_meson`

**Comment by superna9999** [comment]
Sure, I'll do that

**Comment by superna9999** [comment]
Done!
