### ISSUE TITLE
missing nanopi-k2 MACHINE?

### ISSUE THREAD

**Issue by twoerner** [superna9999/meta-meson#24]
There appears to be support for the nanopi-k2 machine (recipes-bsp/u-boot/u-boot-nanopi-k2_v2015.01.bb) but does there need to be a nanopi.conf in conf/machine?

**Comment by superna9999** [comment]
@twoerner I added support on master, but it's broken... TonyMas32 from Armbian did a port for U-boot upstream, I'll add to master ASAP and we will have a working NanopiK2 !

**Comment by superna9999** [comment]
Well, I added it using mainline u-boot and it works, cool !
