### ISSUE TITLE
Logs patch kernel ?

### ISSUE THREAD

**Issue by 150balbes** [superna9999/meta-meson#46]
Hi.
Where can I see the details (logs) of applying patches to the kernel ? I need to see if all the patches (which I add\modify) are applied correctly before building.

**Comment by superna9999** [comment]
You can see in the bitbake do_patch log, I have this info is `tmp/work/libretech_cc-poky-linux/linux-yocto-meson64/4.17.1+gitAUTOINC+d0c077266e-r0/temp/log.do_patch`

**Comment by 150balbes** [comment]
Thank you, I searched all the directories, and the temporary directory is not checked.

**Comment by 150balbes** [comment]
Still a fair question. :) 
Is there a difference in the package composition for the build option ?

export MACHINE=khadas-vim
bitbake core-image-base

and

export MACHINE=khadas-vim-sdboot
bitbake core-image-base

Or, the package composition is determined by the target only core-image-base ?

**Comment by superna9999** [comment]
yes, the MACHINE will use the conf/machine/$MACHINE.conf to determine the needed packages for the machine and it will change some packages if the 2 machine conf files are different.
In this case, it should not change a lot, maybe only the u-boot tools

**Comment by 150balbes** [comment]
When attempting to build version of the image 

export MACHINE=khadas-vim-sdboot
bitbake core-image-base

from the branch topic\v4l2-m2m. I get the error 


patching file arch/arm64/boot/dts/amlogic/meson-gxl.dtsi
Hunk #1 succeeded at 265 with fuzz 1.
ERROR: linux-yocto-meson64-4.17.1+gitAUTOINC+d0c077266e-r0 do_patch: Applying '0003-ASoC-meson-add-meson-audio-core-driver.patch' failed:
checking file sound/soc/Kconfig
Reversed (or previously applied) patch detected!  Assume -R? [n] 
Apply anyway? [n] 
Skipping patch.
1 out of 1 hunk ignored
checking file sound/soc/Makefile
Reversed (or previously applied) patch detected!  Assume -R? [n] 
Apply anyway? [n] 
..........


Does this mean that this patch duplicates another one ?

**Comment by 150balbes** [comment]
Error from patch 0003 - secondary. As it turned out the first mistake goes from patch 0011

ERROR: linux-yocto-meson64-4.17.1+gitAUTOINC+d0c077266e-r0 do_patch: Applying '0011-meson-gxl-add-vdec-support.patch' failed:
checking file arch/arm64/boot/dts/amlogic/meson-gx.dtsi
checking file arch/arm64/boot/dts/amlogic/meson-gxl.dtsi
Hunk #1 succeeded at 807 (offset 2 lines).
checking file drivers/clk/meson/gxbb.c
Hunk #1 succeeded at 1626 (offset 83 lines).
Hunk #2 FAILED at 1835.
Hunk #3 FAILED at 1991.
Hunk #4 FAILED at 2149.
3 out of 4 hunks FAILED
checking file drivers/clk/meson/gxbb.h
Hunk #1 FAILED at 204.
1 out of 1 hunk FAILED
checking file drivers/media/platform/meson/vdec/esparser.c
checking file drivers/media/platform/meson/vdec/vdec.c
checking file drivers/soc/amlogic/meson-pwrc-vdec.c
File gxtvbb_vh264_mc: git binary diffs are not supported.
checking file include/dt-bindings/clock/gxbb-clkc.h
Hunk #1 FAILED at 125.
1 out of 1 hunk FAILED
ERROR: linux-yocto-meson64-4.17.1+gitAUTOINC+d0c077266e-r0 do_patch: Function failed: patch_do_patch
ERROR: Logfile of failure stored in: /home/user/amlogic-bsp/build/tmp/work/khadas_vim_sdboot-poky-linux/linux-yocto-meson64/4.17.1+gitAUTOINC+d0c077266e-r0/temp/log.do_patch.4933
ERROR: Task (/home/user/amlogic-bsp/meta-meson/recipes-kernel/linux/linux-yocto-meson64_4.17.bb:do_patch) failed with exit code '1'

**Comment by superna9999** [comment]
I can't reproduce, are you sure your meta-meson is clean ?

**Comment by 150balbes** [comment]
I can check after I get back from vacation :)
