### ISSUE TITLE
Patch order 4.18

### ISSUE THREAD

**Issue by Tonymac32** [superna9999/meta-meson#57]
Patch order for kernel recipe 4.18.

0001-ARM64-dts-meson-add-vdec-entries.patch needs to be applied after all of the other patches.

**Comment by superna9999** [comment]
Thanks, I'll reorder it !

**Comment by superna9999** [comment]
Actually it's in the right order, but yeah yocto does not use the name to order it.
Couldn't you use a manifest or equivalent to specify the order of patching ?

**Comment by Tonymac32** [comment]
Ah ok.  We just use the name, so all I did was make it number 28 instead of
number 1.  Since it doesn't affect anyone but me I'll close this.
