### ISSUE TITLE
S905W support

### ISSUE THREAD

**Issue by damdinsharav** [superna9999/meta-meson#59]
Hello, I'm just wondering when you can update for S905w?

More specifically for this little guy https://www.cnx-software.com/2017/08/24/x96-mini-amlogic-s905w-android-tv-box-sells-for-25-and-up/

**Comment by superna9999** [comment]
I will add support for meson-gxl-s905w-p281 and meson-gxl-s905w-tx3-mini, rhe p281 should certainly work

**Comment by superna9999** [comment]
Added in 394dbcdab2702b0d4a0f62c5b7b8afc87d482925
