### ISSUE TITLE
Option to select 32bit

### ISSUE THREAD

**Issue by damdinsharav** [superna9999/meta-meson#73]
Is it possible to add option for selecting 32bit image?

**Comment by superna9999** [comment]
Hi, no, under Yocto the rootfs arch is dependent on the kernel arch, so 64bit kernel forces 64bit rootfs, but you can setup multilib to have 32bit binaries on a 64bit rootfs:
https://www.yoctoproject.org/docs/current/dev-manual/dev-manual.html#combining-multiple-versions-library-files-into-one-image
