### ISSUE TITLE
Need support for my customized board (processor: amlogic s905w)

### ISSUE THREAD

**Issue by vasujois** [superna9999/meta-meson#76]
Dear Sir/Madam,

Myself Vasu Joshi. I have a customized board which has Amlogic s905w processor. 

I want to build a sd card image for the same board. Can you please suggest me the steps how to start or is it enough if i follow the steps which is mentioned in the README section? 

Thanks in advance.
Vasu Joshi

**Comment by superna9999** [comment]
The step is to add support for your board on upstream linux, or my customizing the meta-meson kernel, then adding the proper machine conf for your board with the right boot files and sdcard layout.
